---

  AWSTemplateFormatVersion: "2010-09-09"

  Description: "Creates an ECR Respository and Pipeline for a project"

  Parameters:

    Identifier:
      Type: String
      Default: Dockyard
      Description: "Unique identifier for Dockyard within the system."

    GitHubToken:
      Type: String
      NoEcho: true
      Description: "A Github OAuth Token with public_repo or repo scope"

    GitHubUser:
      Type: String
      Description: "Organisation or Username that the repository belongs to"

    Repo:
      Type: String
      Description: "The name of the repository"

    Branch:
      Type: String
      Default: master
      Description: "Branch to use from the repository."

  Metadata:
    AWS::CloudFormation::Interface:
      ParameterGroups:
        - Label:
            default: "GitHub Configuration"
          Parameters:
            - GitHubToken
            - GitHubUser
        - Label:
            default: "Repository Configuration"
          Parameters:
            - Repo
            - Branch
        - Label:
            default: "Dockyard Configuration"
          Parameters:
            - Identifier
      ParameterLabels:
        GitHubToken:
          default: "GitHub Personal Access Token"
        GitHubUser:
          default: "Username or Organisation Name"
        Repo:
          default: "Repository Name"
        Branch:
          default: "Branch on Repository"
        Identifier:
          default: "Dockyard Version"

  Resources:

    Repository:
      Type: "AWS::ECR::Repository"
      Properties:
        RepositoryName:
          Fn::Join:
            - "/"
            -
              - !Ref GitHubUser
              - !Ref Repo

    PipelineArtifactStore:
      Type: "AWS::S3::Bucket"
      Properties:
        VersioningConfiguration:
          Status: Enabled

    Pipeline:
      Type: "AWS::CodePipeline::Pipeline"
      Properties:
        ArtifactStore:
          Location: !Ref PipelineArtifactStore
          Type: S3
        RoleArn:
          Fn::ImportValue: !Sub "${Identifier}RoleArn"
        Stages:
          - Name: Source
            Actions:
              - Name: Source
                RunOrder: 1
                ActionTypeId:
                  Category: Source
                  Owner: ThirdParty
                  Version: 1
                  Provider: GitHub
                OutputArtifacts:
                  - Name:
                      Fn::Join:
                        - "-"
                        -
                          - !Ref Repo
                          - !Ref Branch
                Configuration:
                  Owner: !Ref GitHubUser
                  Repo: !Ref Repo
                  Branch: !Ref Branch
                  OAuthToken: !Ref GitHubToken

          - Name: Build
            Actions:
              - Name: Build
                InputArtifacts:
                  - Name:
                      Fn::Join:
                        - "-"
                        -
                          - !Ref Repo
                          - !Ref Branch
                ActionTypeId:
                  Category: Build
                  Owner: Custom
                  Version:
                    Fn::ImportValue: !Sub "${Identifier}Version"
                  Provider: !Ref Identifier
                OutputArtifacts:
                  - Name:
                      Fn::Join:
                        - "-"
                        -
                          - !Ref Repo
                          - !Ref Branch
                          - Output
                Configuration:
                  image: !Ref Repository


  Outputs:

    Repository:
      Description: "Name of the ECR Repository"
      Value: !Ref Repository
      Export:
        Name: !Sub "${AWS::StackName}Repository"

    RepositoryImage:
      Description: "URL to the ECR Repository"
      Value:
        Fn::Join:
          - ""
          -
            - !Ref AWS::AccountId
            - "dkr.ecr."
            - !Ref AWS::Region
            - "amazonaws.com/"
            - !Ref Repository
            - ":"
            - !Ref Branch
      Export:
        Name: !Sub "${AWS::StackName}RepsitoryImage"
