'use strict';
// tests for poller

// Generated by serverless-mocha-plugin

process.env.NODE_ENV = 'test';

const mod               = require('../handler.js');
const mochaPlugin       = require('serverless-mocha-plugin');
const lambdaWrapper     = mochaPlugin.lambdaWrapper;
const expect            = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-Poller'
};

const Function = mod.poller;

const wrapped = lambdaWrapper.wrap(mod, { handler: 'poller' });

describe('poller #perform', () => {

  before(function (done) {
    lambdaWrapper.init(liveFunction);
    done();
  });

  it('should respond with an object', (done) => {
    wrapped.run({}, (err, response) => {
      expect(response).to.be.empty();
      done();
    });
  });
});
